name: SARS-CoV-2_PRJNA612766
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
  - altair=4.1
  - altair_saver=0.5.0
  - biopython=1.78
  - bwa-mem2=2.2.1
  - entrez-direct=13.9
  - fastp=0.20.1
  - ftputil=5.0.1
  - iqtree=2.1.2
  - jupyterlab>=3
  - mafft=7.475
  - mamba
  - minimap2=2.18
  - natsort
  - openpyxl=3.0.7
  - pandas=1.2.4
  - plotnine=0.8.0
  - pysam=0.16.0.1
  - python=3.8
  - ruamel.yaml=0.17.7
  - samtools=1.12
  - snakemake=6.3.0
  - sra-tools=2.11.0
  - xlrd=2.0.1
